vscode:
  extensions:
    - https://github.com/yogesh-ti/web-extension/raw/main/devspacesplus-0.0.1.vsix

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: start GUI
    init: echo 'init script' # runs during prebuild
    before: gp sync-await multispace
    command: |
      cd react-flask-app
      npm install
      yarn start
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
  - port: 2200
    visibility: public
  - port: 2201
    visibility: public
  - port: 2202
    visibility: public
