execConfig:
  environment:
    API_URL: ${API.TimeEndpoint.Host}/${API.TimeEndpoint.Path}
    RANDOM_ENV: Devspace
endpoints:
  GuiEndpoint:
    port: 3000
    protocol: HTTPS
    path: ''
dependsOn:
  API:
    type: DEVSPACES::REPO::GIT
    properties:
      repoUrl: https://github.com/abhishek-dhanraj-TI/react-flask-api
