name: React Flask App
execConfig:
  environment:
    REACT_APP_API_URL: ${API.TimeEndpoint.devspaceHost}/${API.TimeEndpoint.path}
    REACT_APP_RANDOM_ENV: Devspace
endpoints:
  GuiEndpoint:
    port: 3000
    protocol: HTTPS
    path: ''
dependsOn:
  API:
    type: DEVSPACES::REPO::GIT
    properties:
      repoUrl: https://github.com/abhishek-dhanraj-TI/react-flask-api/tree/ui-api-db
